
spring.application.name=solarshare

spring.datasource.url=jdbc:mysql://localhost:3306/solarshare
spring.datasource.username=root
spring.datasource.password=SUBAHARIPPRIYA@26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html